# A workflow that will run test, build, build-docker-image for latest tag

name: Build and test project

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: ./gradlew test

  build-gradle-project:
    runs-on: ubuntu-latest
    needs: test-gradle-project
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build project
        run: ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: build/libs/*.jar

  build-docker-image:
    runs-on: ubuntu-latest
    needs: test-gradle-project
    # run only on master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Set lowercased repository name
        run: echo "repository_lowercased_name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ env.repository_lowercased_name }}
          image_tag: latest
          github_token: ${{ secrets.GH_PAT }}
