# A workflow that will run test, build, build-docker-image for latest tag

name: Build and test project

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: ./gradlew test

  build-gradle-project:
    runs-on: ubuntu-latest
    needs: test-gradle-project
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build project
        run: ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: build/libs/*.jar

  build-docker-image:
    runs-on: ubuntu-latest
    needs: test-gradle-project
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:master
